version: '2'
services:
    pollitics-app:
        image: pollitics
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pollitics-postgresql:5432/pollitics
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pollitics-postgresql:
        extends:
            file: postgresql.yml
            service: pollitics-postgresql
